### PR TITLE
Add Git section to coding standards

### PR DESCRIPTION
**Pull request by TheeDeafFrog**

### CODE REVIEW

**Comment by Letanyan** [comment]
This seems to be doing a lot more than just adding a git section?

**Comment by TheeDeafFrog** [comment]
Odd, I deleted the web-interface directory in the Website branch yesterday, the change seems to somehow have carried across here.

**Comment by Letanyan** [comment]
Do you want to close this and change it or just go ahead with removing "/webInterface" from Developer branch?

**Comment by TheeDeafFrog** [comment]
Well, it needs to go one way or another.

**Comment by Letanyan** [comment]
Cool then I'll merge. Unless someones depending on WebInterface?

**Pull request merged**
